### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by chb0github** [chrumck/MoniScope#1]
This is a good start and I like the ideas you have. Let's polish them a bit so we can focus our efforts. Also, I have a friend who is a UX designer who might give you some advice if you can get to concrete examples. You see a pet project to showcase your coder skills. I see a business opportunity here. 

Straight from the readme page:

```
work pretty much like Google Maps... except for measurements. The aim is to build a crisp, intuitive interface to show measurements from variety of wireless remote sensors, be it simple temperature gauge in your basement, a voltage and speed sensor in your car, or a complex network of instruments on a construction site to measure the influence of site activities on the surroundings.
```

Google maps is a mapping service. What you have in mind is nothing like it. You want to be able to overlay instrumentation information on top of it and allow users to explore that data. Ideally, your service can find patterns they never knew to look for. 

People will always gravity to concrete examples from their everyday lives because they intuitively understand it.

Next steps:

1. Give a concrete example of a sensor you would like to "monitor" and then quote (even by sample) the kind of data/reports you might like. As a non geo-tech I have no idea what is important in that space. That is the initial market you're targeting. Solve problems they have now.

Here are some important aspects I think we can focus on

1) Realtime analytics and intelligence. Passive data isn't nearly as useful as active data.
2) Concrete simple example/implentations. Is there a sensor out there in the market you would like to emulate/replace? Link me

**Comment by chrumck** [comment]
Yo!

Thanks for your input!

[I put together a draft of the graphical design and the specs here](https://github.com/chrumck/MoniScope/tree/master/DesignAndSpecifications)

Yeah, business opportunity. You're probably right, but at this very point I want to learn to code, not learn how to make business!

Here are some comments to your comments:

```
Google maps is a mapping service. What you have in mind is nothing like it. 
```

Well, I don't agree. Google maps is way more than a mapping service. It's a [GIS](https://en.wikipedia.org/wiki/Geographic_information_system). I think my idea falls within the same category. I want to show spatial data in a nice way, just different data from what Google Maps is serving.

```
Give a concrete example of a sensor you would like to "monitor" and then quote (even by sample) the kind of data/reports you might like. As a non geo-tech I have no idea what is important in that space. That is the initial market you're targeting. Solve problems they have now.
```

[I mentioned this one earlier](https://www.sierrawireless.com/products-and-solutions/routers-gateways/rv50/), Raven RV50

![RV50](https://www.sierrawireless.com/-/media/iot/products/gatewayproductpages/gateways_rv50_475x274.png?la=en)

[You can use its LUA based application framework](http://source.sierrawireless.com/resources/airlink/aleos_af/refdoc_aleos_af_api_1_3/) to make it do whatever you want, including taking measurements of voltage, temp, speed measurement and pushing it via REST. That's the thing I want to try first. I'm going to buy one and mount it in my motorcycle to have data to work with when I spin up the service.
If you want to have a solid example which could compete with what I was doing at my previous job, just take the **RV50** and mate it with [this thingy which measures tilt with (0.01 mm/m) accuracy](http://www.rstinstruments.com/In-Place-Tilt-Meter.html). It talks serial, and the **RV50** has a serial port so it should be easy to make them work together.

```
Here are some important aspects I think we can focus on

  1. Realtime analytics and intelligence. Passive data isn't nearly as useful as active data.

  2. Concrete simple example/implentations. Is there a sensor out there in the market you would like to emulate/replace? Link me
```

ad 1. Uh, what?
as 2. As mentioned above. The trick with the tilt meter is that it is usually connected to a datalogger (which is expensive), and then to a cellular modem. I'm cutting out the datalogger and make the whole thing significantly cheaper. Not all sensors will allow that kind of savings, but I intend to work on other types of instruments and find ways to take advantage of modern hardware to simplify design and decrease cost.

**Comment by chb0github** [comment]
How's the project coming

**Comment by chrumck** [comment]
Well, I'm going to work on exactly the same thing at Geocomp :)
